site_name: My Docs
theme: 
  name: material
  palette:
    # Dark mode
      scheme: slate
      primary: cyan
      accent: amber
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate 
nav:
  - Home: index.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details

